// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductModel;

#nullable disable

namespace ProductModel.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20230315160811_Adding-GRN-Table-Data.")]
    partial class AddingGRNTableData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductModel.GRN", b =>
                {
                    b.Property<int>("GrnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrnID"), 1L, 1);

                    b.Property<string>("DeliveryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StockUpdated")
                        .HasColumnType("bit");

                    b.HasKey("GrnID");

                    b.ToTable("GRNs");

                    b.HasData(
                        new
                        {
                            GrnID = 1,
                            DeliveryDate = "20/03/2022",
                            OrderDate = "23/02/2022",
                            StockUpdated = false
                        },
                        new
                        {
                            GrnID = 2,
                            DeliveryDate = " ",
                            OrderDate = "24/02/2022",
                            StockUpdated = false
                        });
                });

            modelBuilder.Entity("ProductModel.GRNLine", b =>
                {
                    b.Property<int>("LineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineID"), 1L, 1);

                    b.Property<int>("GrnId")
                        .HasColumnType("int");

                    b.Property<int>("QtyDelivered")
                        .HasColumnType("int");

                    b.Property<int>("StockID")
                        .HasColumnType("int");

                    b.HasKey("LineID");

                    b.ToTable("GRNLines");

                    b.HasData(
                        new
                        {
                            LineID = 1,
                            GrnId = 1,
                            QtyDelivered = 20,
                            StockID = 1
                        },
                        new
                        {
                            LineID = 2,
                            GrnId = 1,
                            QtyDelivered = 40,
                            StockID = 2
                        },
                        new
                        {
                            LineID = 3,
                            GrnId = 1,
                            QtyDelivered = 70,
                            StockID = 3
                        },
                        new
                        {
                            LineID = 4,
                            GrnId = 2,
                            QtyDelivered = 20,
                            StockID = 9
                        });
                });

            modelBuilder.Entity("ProductModel.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<int>("ReorderQuantity")
                        .HasColumnType("int");

                    b.Property<int>("StockOnHand")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Chai",
                            ReorderLevel = 10,
                            ReorderQuantity = 14,
                            StockOnHand = 9,
                            UnitPrice = 10.0
                        },
                        new
                        {
                            ID = 2,
                            Description = "Syrup",
                            ReorderLevel = 25,
                            ReorderQuantity = 8,
                            StockOnHand = 10,
                            UnitPrice = 5.0
                        },
                        new
                        {
                            ID = 3,
                            Description = "Cajun Seasoning",
                            ReorderLevel = 10,
                            ReorderQuantity = 17,
                            StockOnHand = 7,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 4,
                            Description = "Olive Oil",
                            ReorderLevel = 10,
                            ReorderQuantity = 16,
                            StockOnHand = 8,
                            UnitPrice = 8.0
                        },
                        new
                        {
                            ID = 5,
                            Description = "Boysenberry Spread",
                            ReorderLevel = 25,
                            ReorderQuantity = 19,
                            StockOnHand = 5,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 6,
                            Description = "Dried Pears",
                            ReorderLevel = 10,
                            ReorderQuantity = 23,
                            StockOnHand = 7,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 7,
                            Description = "Curry Sauce",
                            ReorderLevel = 10,
                            ReorderQuantity = 30,
                            StockOnHand = 6,
                            UnitPrice = 9.0
                        },
                        new
                        {
                            ID = 8,
                            Description = "Walnuts",
                            ReorderLevel = 10,
                            ReorderQuantity = 17,
                            StockOnHand = 1,
                            UnitPrice = 2.0
                        },
                        new
                        {
                            ID = 9,
                            Description = "Fruit Cocktail",
                            ReorderLevel = 10,
                            ReorderQuantity = 29,
                            StockOnHand = 8,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 10,
                            Description = "Chocolate Biscuits Mix",
                            ReorderLevel = 5,
                            ReorderQuantity = 7,
                            StockOnHand = 1,
                            UnitPrice = 2.0
                        },
                        new
                        {
                            ID = 11,
                            Description = "Marmalade",
                            ReorderLevel = 10,
                            ReorderQuantity = 61,
                            StockOnHand = 2,
                            UnitPrice = 10.0
                        },
                        new
                        {
                            ID = 12,
                            Description = "Scones",
                            ReorderLevel = 5,
                            ReorderQuantity = 8,
                            StockOnHand = 5,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 13,
                            Description = "Beer",
                            ReorderLevel = 15,
                            ReorderQuantity = 11,
                            StockOnHand = 4,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 14,
                            Description = "Crab Meat",
                            ReorderLevel = 30,
                            ReorderQuantity = 14,
                            StockOnHand = 3,
                            UnitPrice = 2.0
                        },
                        new
                        {
                            ID = 15,
                            Description = "Clam Chowder",
                            ReorderLevel = 10,
                            ReorderQuantity = 7,
                            StockOnHand = 6,
                            UnitPrice = 10.0
                        },
                        new
                        {
                            ID = 16,
                            Description = "Coffee",
                            ReorderLevel = 25,
                            ReorderQuantity = 35,
                            StockOnHand = 1,
                            UnitPrice = 3.0
                        },
                        new
                        {
                            ID = 17,
                            Description = "Chocolate",
                            ReorderLevel = 25,
                            ReorderQuantity = 10,
                            StockOnHand = 1,
                            UnitPrice = 10.0
                        },
                        new
                        {
                            ID = 18,
                            Description = "Dried Apples",
                            ReorderLevel = 10,
                            ReorderQuantity = 40,
                            StockOnHand = 3,
                            UnitPrice = 1.0
                        },
                        new
                        {
                            ID = 19,
                            Description = "Long Grain Rice",
                            ReorderLevel = 25,
                            ReorderQuantity = 5,
                            StockOnHand = 3,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 20,
                            Description = "Gnocchi",
                            ReorderLevel = 30,
                            ReorderQuantity = 29,
                            StockOnHand = 3,
                            UnitPrice = 8.0
                        },
                        new
                        {
                            ID = 21,
                            Description = "Ravioli",
                            ReorderLevel = 20,
                            ReorderQuantity = 15,
                            StockOnHand = 7,
                            UnitPrice = 5.0
                        },
                        new
                        {
                            ID = 22,
                            Description = "Hot Pepper Sauce",
                            ReorderLevel = 10,
                            ReorderQuantity = 16,
                            StockOnHand = 7,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 23,
                            Description = "Tomato Sauce",
                            ReorderLevel = 20,
                            ReorderQuantity = 13,
                            StockOnHand = 5,
                            UnitPrice = 9.0
                        },
                        new
                        {
                            ID = 24,
                            Description = "Mozzarella",
                            ReorderLevel = 10,
                            ReorderQuantity = 26,
                            StockOnHand = 4,
                            UnitPrice = 9.0
                        },
                        new
                        {
                            ID = 25,
                            Description = "Almonds",
                            ReorderLevel = 5,
                            ReorderQuantity = 8,
                            StockOnHand = 5,
                            UnitPrice = 9.0
                        },
                        new
                        {
                            ID = 26,
                            Description = "Mustard",
                            ReorderLevel = 15,
                            ReorderQuantity = 10,
                            StockOnHand = 3,
                            UnitPrice = 4.0
                        },
                        new
                        {
                            ID = 27,
                            Description = "Dried Plums",
                            ReorderLevel = 50,
                            ReorderQuantity = 3,
                            StockOnHand = 3,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 28,
                            Description = "Green Tea",
                            ReorderLevel = 100,
                            ReorderQuantity = 2,
                            StockOnHand = 2,
                            UnitPrice = 3.0
                        },
                        new
                        {
                            ID = 29,
                            Description = "Granola",
                            ReorderLevel = 20,
                            ReorderQuantity = 2,
                            StockOnHand = 2,
                            UnitPrice = 2.0
                        },
                        new
                        {
                            ID = 30,
                            Description = "Potato Chips",
                            ReorderLevel = 30,
                            ReorderQuantity = 1,
                            StockOnHand = 3,
                            UnitPrice = 5.0
                        },
                        new
                        {
                            ID = 31,
                            Description = "Brownie Mix",
                            ReorderLevel = 10,
                            ReorderQuantity = 9,
                            StockOnHand = 2,
                            UnitPrice = 8.0
                        },
                        new
                        {
                            ID = 32,
                            Description = "Cake Mix",
                            ReorderLevel = 10,
                            ReorderQuantity = 11,
                            StockOnHand = 8,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 33,
                            Description = "Tea",
                            ReorderLevel = 20,
                            ReorderQuantity = 2,
                            StockOnHand = 3,
                            UnitPrice = 4.0
                        },
                        new
                        {
                            ID = 34,
                            Description = "Pears",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 10,
                            UnitPrice = 1.0
                        },
                        new
                        {
                            ID = 35,
                            Description = "Peaches",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 7,
                            UnitPrice = 7.0
                        },
                        new
                        {
                            ID = 36,
                            Description = "Pineapple",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 1,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 37,
                            Description = "Cherry Pie Filling",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 10,
                            UnitPrice = 2.0
                        },
                        new
                        {
                            ID = 38,
                            Description = "Green Beans",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 2,
                            UnitPrice = 9.0
                        },
                        new
                        {
                            ID = 39,
                            Description = "Corn",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 3,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 40,
                            Description = "Peas",
                            ReorderLevel = 10,
                            ReorderQuantity = 1,
                            StockOnHand = 3,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 41,
                            Description = "Tuna Fish",
                            ReorderLevel = 30,
                            ReorderQuantity = 1,
                            StockOnHand = 8,
                            UnitPrice = 2.0
                        },
                        new
                        {
                            ID = 42,
                            Description = "Smoked Salmon",
                            ReorderLevel = 30,
                            ReorderQuantity = 2,
                            StockOnHand = 9,
                            UnitPrice = 10.0
                        },
                        new
                        {
                            ID = 43,
                            Description = "Hot Cereal",
                            ReorderLevel = 50,
                            ReorderQuantity = 3,
                            StockOnHand = 8,
                            UnitPrice = 6.0
                        },
                        new
                        {
                            ID = 44,
                            Description = "Vegetable Soup",
                            ReorderLevel = 100,
                            ReorderQuantity = 1,
                            StockOnHand = 4,
                            UnitPrice = 9.0
                        },
                        new
                        {
                            ID = 45,
                            Description = "Chicken Soup",
                            ReorderLevel = 100,
                            ReorderQuantity = 1,
                            StockOnHand = 2,
                            UnitPrice = 8.0
                        });
                });

            modelBuilder.Entity("ProductModel.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Address = "49 Gilbert St.",
                            City = "London",
                            CompanyName = "Exotic Liquids",
                            ContactName = "Charlotte Cooper",
                            ContactTitle = "Purchasing Manager",
                            Country = "UK",
                            Phone = "(171) 555-2222",
                            PostalCode = "EC1 4SD",
                            Region = "NULL"
                        },
                        new
                        {
                            SupplierID = 2,
                            Address = "P.O. Box 78934",
                            City = "New Orleans",
                            CompanyName = "New Orleans Cajun Delights",
                            ContactName = "Shelley Burke",
                            ContactTitle = "Order Administrator",
                            Country = "USA",
                            Phone = "(100) 555-4822",
                            PostalCode = "70117",
                            Region = "LA"
                        },
                        new
                        {
                            SupplierID = 3,
                            Address = "707 Oxford Rd.",
                            City = "Ann Arbor",
                            CompanyName = "Grandma Kelly's Homestead",
                            ContactName = "Regina Murphy",
                            ContactTitle = "Sales Representative",
                            Country = "USA",
                            Phone = "(313) 555-5735",
                            PostalCode = "48104",
                            Region = "MI"
                        },
                        new
                        {
                            SupplierID = 4,
                            Address = "9-8 Sekimai Musashino-shi",
                            City = "Tokyo",
                            CompanyName = "Tokyo Traders",
                            ContactName = "Yoshi Nagase",
                            ContactTitle = "Marketing Manager",
                            Country = "Japan",
                            Phone = "(03) 3555-5011",
                            PostalCode = "100",
                            Region = "NULL"
                        });
                });

            modelBuilder.Entity("ProductModel.Product", b =>
                {
                    b.HasOne("ProductModel.Supplier", null)
                        .WithMany("SupplierProducts")
                        .HasForeignKey("SupplierID");
                });

            modelBuilder.Entity("ProductModel.Supplier", b =>
                {
                    b.Navigation("SupplierProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
